name: soochit
description: Not just another medicine reminder.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  numeric_keyboard: ^1.0.0
  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.15.5+3
  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  provider: ^4.0.4
  cloud_firestore: ^0.13.6
  firebase_storage: ^3.0.6
  flutter_local_notifications: ^1.4.4+1
  rxdart: ^0.24.1
  path_provider: ^1.6.11
  http: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  mobx_codegen: ^1.0.3

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: airbnb
      fonts:
        - asset: assets/fonts/AirbnbCereal-Bold.ttf
          weight: 800

    - family: lexenddeca
      fonts:
        - asset: assets/fonts/LexendDeca-Regular.ttf

  assets:
    - assets/images/